app:
    runmode: debug
db:
    host: 127.0.0.1:3316
    username: root
    password: "testpassword"
    database: testdb
    max-idle-connections: 10
    max-open-connections: 100
    max-connection-life-time: 10s
    log-level: 1
get_image:
    random_public_limit: 50
image:
    ImageMaxSize: 20971520
    image_dir: temp_image
    Convert:
        WebPQuality: 80
        WebReductionEffort: 4
        AvifQuality: 60
        AvifEffort: 4
        ImageLossless: false
    MaxTagCount: 20
jwt:
    secret: demo520-secret-key
log:
    disable-caller: false
    disable-stacktrace: false
    level: info
    encoding: console
    output-paths:
        - stdout
login:
    timing_attack_protection: 5
server:
    addr: :8080
